version: '3.9'
services:
  mongodb:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  # mongo_express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
  task_manager:
    depends_on:
      - mongodb
    build: .
    ports:
      - 3000:3000
    environment:
      DB_URI: mongodb://mongodb:27017/
      DB_USERNAME: mongoadmin
      DB_PASSWORD: secret
      DB: task_manager
      CONNECTION_TYPE: authMechanism=DEFAULT
      WAIT_HOSTS: mongodb:27017
    restart: unless-stopped
